### ISSUE TITLE
CNApp web to mark genes on frequency plots

### ISSUE THREAD

**Issue by shwetagodbole** [ait5/CNApp#2]
First of all, thank you so much for developing CNApp web! A very nice app that performs all tasks. However, I was wondering if I can somehow select certain genes generated in the gene list when we perform region profiling and mark them on the plot? I wanted to check whether they have been gained or lost. 

Thanks once again and I look forward to your response! 

Shweta

**Comment by ait5** [comment]
Hi, thanks for using our app and really sorry for my delay!

We do not have that option... you should download the data associated to that plot and try to add the names by plotting on your end.

Thanks again,
Sebastià
